### ISSUE TITLE
Catch exception during processing

### ISSUE THREAD

**Issue by jonas-grgt** [toolisticon/cute#84] opened 2024-03-19 20:21 UTC
Hi, first of all many thanks for putting in the effort for creating and maintaining this library! 

I have a use-case which I can't seem to cover. After diving into the code I either misunderstand how the library should be used or it is a missing functionality.

During processing my Annotation Processor might throw a certain exception deliberately. I want to test this behavior using a `blackBoxTest`.

I couldn't find any methods that pointed me the coping with failure except `compilationFails`. It is not clear to me if this method is there to verify that the generated files are able to compile or if the processing succeeded?

I found a `getExceptionIsThrown` inside the `Cute` class but this is only used within a `unitTest` scenario, is this an overlooked feature for a `blackboxTest`.

I was able to fix it myself locally by extending `BlackBoxTestOutcomeInterface` with a similar method as it's unit-test counterpart:

```java
CompilerTestExpectAndThatInterface exceptionIsThrown(@FluentApiBackingBeanMapping(value = "exceptionIsThrown") Class<? extends Exception> exception);
```

I would like to contribute this and also add an extra assert that allows me to verify the message inside the exception. It was not clear to me which branch I should start from, master or develop?

**Comment by tobiasstamann** [comment] 2024-03-19 22:00
Hi Jonas,

I had a check in the library before version 1.0.0 that allowed to test for exceptions thrown by a specific processor.

With the new api i decided to remove it, because this usually processors should handle all exceptions internally and to convert them to compiler messages, changing the compiler outcome as needed.

I am completely open to add it again if it is needed by you. But the question is if the expected exception should checked against a specific processor again in case when there is just one processor or to expect it globally.
What do you think?
Please create the PR based on develop.

About your other question: compilationFails does relate tom the compiling process and is a check if all source files and generated source files have been compiled without error.

Best regards

Tobias

**Comment by tobiasstamann** [comment] 2024-03-20 09:21
Hi,

good to hear that the issue is fixed now. 

The feature is relatively new and i had used it myself just in simple tests.

The release is triggered now and will be available with version  1.3.0.

Thanks for filing that issue :)

Best regards

Tobias

**Comment by tobiasstamann** [comment] 2024-03-20 10:30
Sorry, had closed wrong issue by accident

**Comment by tobiasstamann** [comment] 2024-03-20 11:19
Hi @jonas-grgt,

I have prepared and tested the change to apply such a global exception check.

Test results were ok. I will add it with remark in Javadoc that it's discouraged to let a processor throw exceptions and that it is better to convert them to compiler messages and outcome (trigger compiler error).

The release will be done later today, so the change will be available tomorrow with version 1.4.0.

Best regards

Tobias

**Comment by tobiasstamann** [comment] 2024-03-20 11:34
Release has been triggered now.

**Closed by tobiasstamann** 2024-03-20 11:34 UTC

**Comment by jonas-grgt** [comment] 2024-03-20 19:11
Thank you for doing this. You are were fast.

Indeed, I misunderstood the processing API and I should indeed catch specific exceptions and translate them to compiler error messages, thanks for pointing this out.
